import rospy
import numpy as np
from virtual_track.msg import ego_traj 

class EgoTrajSub:
    '''
    Subscribes to the ego trajectories generated by the MPC Safety Filter
    '''

    def __init__(self):
        x = [2.0, 2.0, 2.0, 2.0, 2.0]
        y = [0.0, -0.1, -0.2, -0.3, -0.4]
        self.data = ego_traj(x, y)
        self.ego_traj_sub = rospy.Subscriber('ego_traj', ego_traj, self.callback)

    def callback(self, data):
        self.data = data

    def get_ego_traj(self):
        return self.data

    def get_ego_x_traj(self):
        return self.data.x

    def get_ego_y_traj(self):
        return self.data.y
